### ISSUE TITLE
Issue with type of RefObject<HTMLElement>

### ISSUE THREAD

**Issue by samarpanda** [HenrikDK2/preact-intersection-observer#2]
# Issue with type of RefObject<HTMLElement>

![Screenshot 2022-07-13 at 2 15 11 AM](https://user-images.githubusercontent.com/802163/178779765-fe00c110-cbfb-43c7-9dc3-8f19cc8e736b.png)

## Can we accept this as a solution?

```js
type ReturnArr = [ref: RefObject<any>, inView: boolean];
```

I couldn't figure out what anything other than `any` that would be one of the right fit here.

Can anyone suggest? If you think any is fine. Then i can create an PR as per that.

**Comment by HenrikDK2** [comment]
Instead of using type any, I think the best solution would be to constrain the type to only work with elements that have every property of HTMLElement.

Since elements like HTMLDivElement are extended from HTMLElement this should be a much cleaner solution.
 
So in the upcoming update 1.1.0 you would have to define the ref element in the function like so.
`const [ref, inView] = useObserver<HTMLDivElement>();`
